const DB = (() => {
  const years = [2023, 2024, 2025, 2026];
  const closedDates = [], lots = [], sales = [], wastes = [];
  const products = [
    ['赤バラ','バラ',1000,430],['白バラ','バラ',950,410],['ピンクバラ','バラ',900,390],
    ['白菊','菊',500,160],['黄菊','菊',450,150],['ユリ','ユリ',1200,520],
    ['トルコキキョウ白','草花',700,280],['カーネーション赤','草花',450,180],['ガーベラMIX','草花',350,120],
    ['アルストロメリア','草花',400,150],['ヒマワリ','草花',500,180],['枝物・葉物MIX','枝物',600,240],
    ['カスミソウ','草花',550,190],['デルフィニウム','草花',650,230],['スターチス','草花',380,130],
    ['スプレーマム','菊',420,145],['ダリア','草花',800,330],['季節枝物','枝物',700,270]
  ].map(([name,group,sell,cost]) => ({name,group,sell,cost}));
  const supplierNames = ['常陸ローズファーム','北総フラワー','房総グリーン','筑波花卉園','霞ヶ浦園芸','湘南フラワーズ','武蔵花園','千葉中央園芸','利根生花生産組合','鹿島フラワー','銚子グリーン','成田花園','水戸園芸','土浦フラワー','柏花卉','川越園芸','横浜フラワー','多摩グリーン','江戸川園芸','つくば中央花卉'];
  const regions = ['茨城','千葉','東京','埼玉','神奈川','栃木'];
  const types = ['個人生産者','生産組合','市場・仲卸','法人農園'];
  const suppliers = supplierNames.map((name,i) => ({id:'S'+String(i+1).padStart(3,'0'),name,type:types[i%4],region:regions[i%6],focus:['バラ・季節切花','菊・仏花商材','草花MIX','枝物・葉物'][i%4],leadTime:['1〜2日','2〜3日','2〜4日','3〜5日'][i%4],purchasePolicy:['産地直送。規格と採花日を事前確認。','定番品を週次で計画発注。','相場と予約量を見て追加発注。','季節・イベント前に前倒し確保。'][i%4],riskFocus:['品質差・出荷予定','数量不足・天候','相場変動・追加可否','規格差・納期'][i%4],contactMethod:['電話','WEB','営業担当','FAX'][i%4],qualityMemo:['繁忙期は規格差に注意','入荷時の鮮度を確認','ロット差を記録','開花度を要確認'][i%4],terms:['市場精算','月末締翌月20日','都度精算','月末締翌月末'][i%4]}));
  const bases = ['青葉生花店','花みずき','フローラ東京','白雲葬祭','セレモニー花苑','ブライダルブーケ','彩花ウェディング','マルシェフラワー','グリーンマート','ホーム花園','フラワーパック','東京花束センター','中央花材','東都フラワー','花市場サービス','さくら生花','ローズガーデン','花の駅','華彩堂','フルール'];
  const segments = ['生花専門店','葬儀・祭壇','ブライダル','スーパー','ホームセンター','花束加工','場外卸','イベント装花'];
  const areas = ['東京23区','東京都下','千葉','神奈川','埼玉','茨城'];
  const customers = Array.from({length:100}, (_,i) => { const segment=segments[i%segments.length], rank=i%10<3?'A':i%10<7?'B':'C'; return {id:'C'+String(i+1).padStart(3,'0'),name:bases[i%bases.length]+' '+(i+1)+'号',segment,region:areas[(i*3)%areas.length],rank,usualProducts:segment==='葬儀・祭壇'?'白菊・ユリ・白系':segment==='ブライダル'?'バラ・トルコキキョウ':segment==='スーパー'?'季節花・花束商材':'バラ・季節花・小ロット多品種',businessProfile:segment==='葬儀・祭壇'?'案件発生型。納期優先で緊急発注あり。':segment==='ブライダル'?'週末案件の予約仕入が中心。':'店頭・定番販売を中心に週次で仕入。',preferredChannel:['電話・WEB','電話','WEB','FAX','営業担当'][i%5],buyingPattern:['週次定期','案件発生','事前予約','小刻み追加','月間計画'][i%5],paymentTerms:['月末締翌月20日','月末締翌月末','都度精算'][i%3],managerMemo:['朝の追加注文あり。','価格より鮮度を重視。','イベント前は数量増。','価格交渉が発生しやすい。','定番品は継続性高い。'][i%5],priority:['小回り','納期','品質','価格','安定供給'][i%5]}; });
  let seed = 0x4b4f5307; const rnd=()=>{seed=(Math.imul(seed,1664525)+1013904223)>>>0;return seed/4294967296},ri=(a,b)=>Math.floor(rnd()*(b-a+1))+a,pick=a=>a[Math.floor(rnd()*a.length)],pad=n=>String(n).padStart(2,'0');
  const growth={2023:.90,2024:.96,2025:1,2026:1.08},season={1:.82,2:.88,3:1.18,4:1.02,5:1.12,6:.97,7:1.03,8:1.28,9:1,10:1.06,11:1.10,12:1.35}; let lid=1,tid=1;
  function chooseCustomer(product){let pool=customers;if(product.group==='菊'&&rnd()<.55)pool=customers.filter(c=>['葬儀・祭壇','生花専門店','スーパー'].includes(c.segment));else if(product.group==='バラ'&&rnd()<.45)pool=customers.filter(c=>['ブライダル','生花専門店','イベント装花'].includes(c.segment));else if(rnd()<.25)pool=customers.filter(c=>c.rank==='A');return pick(pool.length?pool:customers)}
  for(const y of years){for(let m=1;m<=12;m++){const last=new Date(y,m,0).getDate();for(let d=1;d<=last;d++){const date=`${y}-${pad(m)}-${pad(d)}`,dow=new Date(date+'T00:00:00').getDay();if(dow===2){closedDates.push(date);continue}const wk=[1,3,5].includes(dow)?1.14:(dow===0||dow===6?.82:.95),factor=season[m]*wk*growth[y],lotCount=Math.max(5,Math.round((10+ri(0,6))*season[m]*([1,3,5].includes(dow)?1.08:.88)));for(let z=0;z<lotCount;z++){const product=pick(products),supplier=pick(suppliers),qty=Math.max(8,Math.round(ri(16,72)*factor)),cost=Math.max(50,Math.round(product.cost*(.86+rnd()*.28)/10)*10),initialPrice=Math.max(100,Math.round(product.sell*(.88+rnd()*.26)/10)*10),wasteQty=rnd()<.33?ri(0,Math.max(1,Math.round(qty*.055))):0,remainQty=rnd()<.14?ri(0,Math.max(1,Math.round(qty*.035))):0,soldQty=Math.max(0,qty-wasteQty-remainQty),markdowns=rnd()<.18?ri(2,4):(rnd()<.47?1:0),lotId='H'+String(y).slice(2)+'L'+String(lid++).padStart(6,'0'),stages=[];let left=soldQty;const stageCount=Math.min(Math.max(1,markdowns+1),Math.max(1,Math.min(4,soldQty)));for(let st=0;st<stageCount;st++){const rs=stageCount-st;let sq=st===stageCount-1?left:Math.max(1,Math.min(left-(rs-1),Math.round(left*(.22+rnd()*.42))));left-=sq;const step=st===0?0:Math.min(markdowns,st),price=Math.max(100,Math.round(initialPrice*Math.pow(.82,step)/10)*10),hour=Math.min(16,8+st*2+ri(0,1));stages.push({step,time:`${pad(hour)}:00`,price,soldQty:sq,reason:['販売開始','販売速度が想定より弱い','相場下落へ対応','在庫消化を優先','閉場時間が近い'][Math.min(step,4)]});let sl=sq,tx=Math.max(1,Math.min(3,ri(1,3),sq));for(let q=0;q<tx;q++){const rt=tx-q,qq=q===tx-1?sl:Math.max(1,Math.min(sl-(rt-1),Math.round(sl*(.28+rnd()*.38))));sl-=qq;const c=chooseCustomer(product);let orderType=pick(['通常','通常','通常','予約','予約','追加','緊急','特別']);if(c.segment==='葬儀・祭壇'&&rnd()<.28)orderType='緊急';if(c.segment==='ブライダル'&&rnd()<.30)orderType='予約';const h=Math.min(17,Math.max(6,hour+ri(-2,2))),minute=pick(['00','10','20','30','40','50']);sales.push({id:'H'+String(y).slice(2)+'T'+String(tid++).padStart(7,'0'),date,year:y,month:m,time:`${pad(h)}:${minute}`,customerId:c.id,customer:c.name,segment:c.segment,region:c.region,orderType,channel:pick(['電話','WEB','FAX','営業担当','店頭']),product:product.name,group:product.group,initialPrice,price,markdownStep:step,qty:qq,amount:price*qq,lotId})}}lots.push({id:lotId,date,year:y,supplierId:supplier.id,product:product.name,group:product.group,qty,cost,purchaseAmount:qty*cost,initialPrice,soldQty,wasteQty,remainQty,stages});if(wasteQty>0)wastes.push({date,lotId,product:product.name,qty:wasteQty,cost,reason:pick(['販売期限超過','品質劣化','傷み','規格外','需要不足'])})}}}}}
  return {years,closedDates,suppliers,customers,products,lots,sales,wastes};
})();
