const yen=n=>'¥'+Math.round(n||0).toLocaleString('ja-JP'); const pct=n=>(n*100).toFixed(1)+'%'; const sum=(a,f)=>a.reduce((s,x)=>s+f(x),0);
const custMap=Object.fromEntries(DB.customers.map(x=>[x.id,x])); const supMap=Object.fromEntries(DB.suppliers.map(x=>[x.id,x])); const lotMap=Object.fromEntries(DB.lots.map(x=>[x.id,x]));
const pill=x=>`<span class="pill ${x==='緊急'?'red':x==='予約'?'blue':x==='追加'?'orange':'green'}">${x}</span>`;
function metric(label,value,sub='',cls=''){return `<div class="card metric"><div class="label">${label}</div><div class="value ${cls}">${value}</div><div class="sub">${sub}</div></div>`}
function group(arr,key){const o={};arr.forEach(x=>{const k=typeof key==='function'?key(x):x[key];(o[k]??=[]).push(x)});return o}
function agg(arr,key){const o={};arr.forEach(x=>{const k=typeof key==='function'?key(x):x[key];o[k]??={rev:0,qty:0,count:0,customers:new Set(),initial:0};o[k].rev+=x.amount;o[k].qty+=x.qty;o[k].count++;o[k].customers.add(x.customerId);o[k].initial+=x.initialPrice*x.qty});return o}
function entriesAgg(o){return Object.entries(o).map(([name,v])=>({name,...v,customerCount:v.customers?.size||0,avg:v.qty?v.rev/v.qty:0,realization:v.initial?v.rev/v.initial:0}))}
function barList(id,rows,n=8,valueKey='rev'){const el=document.getElementById(id);const a=[...rows].sort((x,y)=>y[valueKey]-x[valueKey]).slice(0,n);const mx=Math.max(1,...a.map(x=>x[valueKey]));el.innerHTML=a.map((x,i)=>`<div class="barrow"><div class="barlabel"><span>${i+1}. ${x.name}</span><strong>${yen(x[valueKey])}</strong></div><div class="bar"><span style="width:${x[valueKey]/mx*100}%"></span></div></div>`).join('')||'<div class="muted">データなし</div>'}
function navInit(){document.querySelectorAll('.nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.screen).classList.add('active')})}
function goto(id){document.querySelector(`.nav button[data-screen="${id}"]`).click()}
function deltaHtml(v){return `<span class="delta ${v>=0?'pos':'neg'}">${v>=0?'+':''}${yen(v)}</span>`}
function comparePct(a,b){if(!a)return b?'+∞':'0.0%';return ((b-a)/a*100).toFixed(1)+'%'}
function monthlyTotals(year){const a=Array(12).fill(0);DB.sales.filter(x=>x.year===year).forEach(x=>a[x.month-1]+=x.amount);return a}
function svgLineCompare(y){const py=y-1,a=monthlyTotals(py),b=monthlyTotals(y),mx=Math.max(...a,...b,1),W=820,H=240,p=34,step=(W-p*2)/11;monthlyChartTitle.textContent=`月別売上：${py} vs ${y}`;let s=`<svg viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">`;for(let i=0;i<5;i++){const yy=p+(H-p*2)*i/4;s+=`<line x1="${p}" y1="${yy}" x2="${W-p}" y2="${yy}" stroke="#e8ecf2"/>`}const pts=(arr)=>arr.map((v,i)=>`${p+i*step},${H-p-(v/mx)*(H-p*2)}`).join(' ');s+=`<polyline points="${pts(a)}" fill="none" stroke="#aeb7c7" stroke-width="3"/><polyline points="${pts(b)}" fill="none" stroke="#3154d5" stroke-width="4"/>`;b.forEach((v,i)=>{s+=`<circle cx="${p+i*step}" cy="${H-p-(b[i]/mx)*(H-p*2)}" r="4" fill="#3154d5"/><text x="${p+i*step}" y="${H-8}" text-anchor="middle" font-size="10" fill="#6c7788">${i+1}月</text>`});s+=`<text x="${p}" y="16" font-size="11" fill="#a0a9b8">${py}</text><text x="${p+52}" y="16" font-size="11" fill="#3154d5">${y}</text></svg>`;monthlyChart.innerHTML=s}
function renderDashboard(){const y=+dashYear.value,py=y-1,cur=DB.sales.filter(x=>x.year===y),prev=DB.sales.filter(x=>x.year===py),rev=sum(cur,x=>x.amount),prevRev=sum(prev,x=>x.amount),qty=sum(cur,x=>x.qty),md=cur.filter(x=>x.markdownStep>0),cust=new Set(cur.map(x=>x.customerId)).size,avg=qty?rev/qty:0;dashMetrics.innerHTML=[metric(`${y}売上`,yen(rev),`${py}比 ${comparePct(prevRev,rev)}`,rev>=prevRev?'good':'bad'),metric('販売数量',qty.toLocaleString()+'本',`${cur.length.toLocaleString()}明細`),metric('平均実売単価',yen(avg),'数量加重平均'),metric('値下げ明細率',pct(md.length/cur.length),`${md.length.toLocaleString()}明細`),metric('稼働顧客',cust+'件','顧客マスタ100件')].join('');barList('dashSegBars',entriesAgg(agg(cur,'segment')),9);dashProd.innerHTML=rankSimple(entriesAgg(agg(cur,'product')),10);dashCust.innerHTML=rankSimple(entriesAgg(agg(cur,'customer')),10);dashOrder.innerHTML=rankSimple(entriesAgg(agg(cur,'orderType')),5);svgLineCompare(y)}
function rankSimple(rows,n){return [...rows].sort((a,b)=>b.rev-a.rev).slice(0,n).map((x,i)=>`<div class="barlabel" style="padding:6px 0;border-bottom:1px solid var(--line)"><span>${i+1}. ${x.name}</span><strong>${yen(x.rev)}</strong></div>`).join('')}
function localDateStr(d){return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function validDailyDate(ds){return ds||'2026-08-31'}
function jpDate(ds){const [y,m,d]=ds.split('-').map(Number);return `${y}年${m}月${d}日`}
function weekdayName(ds){const d=new Date(ds+'T00:00:00');return ['日','月','火','水','木','金','土'][d.getDay()]}
function weekdayClass(ds){const w=new Date(ds+'T00:00:00').getDay();return w===0?'sun':w===6?'sat':w===2?'tue':''}
function moveDaily(delta){const d=new Date(validDailyDate(dailyDate.value)+'T00:00:00');d.setDate(d.getDate()+delta);if(d<new Date('2023-01-01T00:00:00')||d>new Date('2026-12-31T00:00:00'))return;dailyDate.value=localDateStr(d);dailyMonth.value=dailyDate.value.slice(0,7);renderDaily()}
let dailySort={key:'amount',dir:-1};
function sortRows(rows,spec){const [key,dirTxt]=spec.split(':');const dir=Number(dirTxt);return [...rows].sort((x,y)=>{const A=x[key],B=y[key];return (A>B?1:A<B?-1:0)*dir})}
function renderDailyMonth(selected){const ym=dailyMonth.value||selected.slice(0,7);const [y,m]=ym.split('-').map(Number);const last=new Date(y,m,0).getDate();let rows=[];for(let d=1;d<=last;d++){const ds=`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;const a=DB.sales.filter(x=>x.date===ds);const rev=sum(a,x=>x.amount),qty=sum(a,x=>x.qty),count=a.length,avg=qty?rev/qty:0,md=count?a.filter(x=>x.markdownStep>0).length/count:0;rows.push({date:ds,rev,qty,count,avg,md,closed:DB.closedDates.includes(ds)})}const mode=dailyMonthSort.value;if(mode==='revDesc')rows.sort((a,b)=>b.rev-a.rev);else if(mode==='qtyDesc')rows.sort((a,b)=>b.qty-a.qty);else if(mode==='countDesc')rows.sort((a,b)=>b.count-a.count);else rows.sort((a,b)=>a.date.localeCompare(b.date));dailyMonthRows.innerHTML=rows.map(r=>`<tr class="${r.date===selected?'selected ':''}${r.closed?'closed':''}" data-date="${r.date}"><td><button class="date-button" data-date="${r.date}">${jpDate(r.date)}</button></td><td><span class="weekday ${weekdayClass(r.date)}">${weekdayName(r.date)}</span>${r.closed?' 定休':''}</td><td class="right">${yen(r.rev)}</td><td class="right">${r.qty.toLocaleString()}</td><td class="right">${r.count}</td><td class="right">${r.qty?yen(r.avg):'—'}</td><td class="right">${r.count?pct(r.md):'—'}</td></tr>`).join('');dailyMonthRows.querySelectorAll('[data-date]').forEach(el=>el.onclick=()=>{dailyDate.value=el.dataset.date;dailyMonth.value=el.dataset.date.slice(0,7);renderDaily()})}
function renderDaily(){let ds=validDailyDate(dailyDate.value);dailyDate.value=ds;if(!dailyMonth.value)dailyMonth.value=ds.slice(0,7);const a=DB.sales.filter(x=>x.date===ds);const rev=sum(a,x=>x.amount),qty=sum(a,x=>x.qty),urgent=a.filter(x=>x.orderType==='緊急').length,md=a.filter(x=>x.markdownStep>0).length;const isClosed=DB.closedDates.includes(ds);dailyDateTitle.textContent=`${jpDate(ds)}（${weekdayName(ds)}）`;dailyDayState.textContent=isClosed?'火曜定休・販売なし':`${a.length.toLocaleString()}明細を分析`;dailyKpis.innerHTML=`<div class="mini"><span class="tiny">日売上</span><br><b>${yen(rev)}</b></div><div class="mini"><span class="tiny">販売数量</span><br><b>${qty.toLocaleString()}本</b></div><div class="mini"><span class="tiny">明細数</span><br><b>${a.length}</b></div><div class="mini"><span class="tiny">緊急</span><br><b>${urgent}</b></div><div class="mini"><span class="tiny">値下げ明細</span><br><b>${md}</b></div>`;
renderDailyMonth(ds);
const hourly=[...new Set(a.map(x=>x.time.slice(0,2)))].sort().map(h=>{const z=a.filter(x=>x.time.startsWith(h+':'));return {name:`${Number(h)}時台`,hour:h,rev:sum(z,x=>x.amount),qty:sum(z,x=>x.qty),count:z.length,avg:sum(z,x=>x.qty)?sum(z,x=>x.amount)/sum(z,x=>x.qty):0}});const peak=[...hourly].sort((x,y)=>y.rev-x.rev)[0];const times=a.map(x=>x.time).sort();dailyTimeKpis.innerHTML=`<div class="mini"><span class="tiny">最初の販売</span><b>${times[0]||'—'}</b></div><div class="mini"><span class="tiny">売上ピーク</span><b>${peak?peak.name:'—'}</b><span class="tiny">${peak?yen(peak.rev):''}</span></div><div class="mini"><span class="tiny">最後の販売</span><b>${times[times.length-1]||'—'}</b></div>`;barList('dailyHourBars',[...hourly].sort((x,y)=>y.rev-x.rev),11);dailyHourRows.innerHTML=hourly.map(x=>`<tr><td>${x.name}</td><td class="right">${yen(x.rev)}</td><td class="right">${x.qty}</td><td class="right">${x.count}</td><td class="right">${yen(x.avg)}</td></tr>`).join('')||'<tr><td colspan="5">販売なし</td></tr>';
const prods=entriesAgg(agg(a,'product')).sort((x,y)=>y.rev-x.rev),custs=entriesAgg(agg(a,'customer')).sort((x,y)=>y.rev-x.rev),segs=entriesAgg(agg(a,'segment')).sort((x,y)=>y.rev-x.rev);barList('dailyProdBars',prods,6);barList('dailyCustBars',custs,6);barList('dailySegBars',segs,6);dailyProdRows.innerHTML=prods.slice(0,20).map((x,i)=>`<tr><td><span class="rank">${i+1}</span></td><td>${x.name}</td><td class="right">${yen(x.rev)}</td><td class="right">${x.qty}</td><td class="right">${yen(x.avg)}</td></tr>`).join('');dailyCustRows.innerHTML=custs.slice(0,20).map((x,i)=>{const seg=a.find(z=>z.customer===x.name)?.segment||'';return `<tr><td><span class="rank">${i+1}</span></td><td>${x.name}</td><td>${seg}</td><td class="right">${yen(x.rev)}</td></tr>`}).join('');dailySegRows.innerHTML=segs.map((x,i)=>`<tr><td><span class="rank">${i+1}</span></td><td>${x.name}</td><td class="right">${yen(x.rev)}</td><td class="right">${x.customerCount}</td></tr>`).join('');
const bands=[['〜299',0,299],['300〜499',300,499],['500〜699',500,699],['700〜999',700,999],['1,000〜',1000,1e9]].map(([name,lo,hi])=>{const z=a.filter(x=>x.price>=lo&&x.price<=hi);return {name,rev:sum(z,x=>x.amount),qty:sum(z,x=>x.qty),count:z.length}});barList('dailyPriceBars',bands,5);dailyPriceRows.innerHTML=[...bands].sort((x,y)=>y.rev-x.rev).map(x=>`<tr><td>${x.name}</td><td class="right">${yen(x.rev)}</td><td class="right">${x.qty}</td><td class="right">${x.count}</td></tr>`).join('');
const sorted=sortRows(a,`${dailySort.key}:${dailySort.dir}`);dailyDetailRows.innerHTML=sorted.map(x=>`<tr><td>${jpDate(x.date)}</td><td>${x.time}</td><td>${x.customer}</td><td>${x.segment}</td><td>${x.product}</td><td>${pill(x.orderType)}</td><td class="right">${yen(x.initialPrice)}</td><td class="right">${yen(x.price)}</td><td class="right">${x.qty}</td><td class="right">${yen(x.amount)}</td></tr>`).join('')||'<tr><td colspan="10">定休または販売なし</td></tr>';renderSameDayHistory(ds)}
function renderSameDayHistory(ds){const parts=ds.split('-').map(Number),m=parts[1],d=parts[2];dailySameDayTitle.textContent=`${m}月${d}日を2023〜2026年で比較`;let prev=null;const rows=DB.years.map(y=>{const last=new Date(y,m,0).getDate(),valid=d<=last,date=valid?`${y}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`:'';const a=valid?DB.sales.filter(x=>x.date===date):[],rev=sum(a,x=>x.amount),qty=sum(a,x=>x.qty),avg=qty?rev/qty:0,delta=prev===null?null:rev-prev;const r={y,date,valid,rev,qty,avg,delta};prev=rev;return r});barList('dailySameDayBars',rows.map(r=>({name:String(r.y),rev:r.rev,qty:r.qty})),4);dailySameDayRows.innerHTML=rows.map(r=>`<tr class="${r.y===parts[0]?'period-highlight':''}"><td><strong>${r.y}</strong></td><td>${r.valid?jpDate(r.date):'該当日なし'}</td><td class="right">${yen(r.rev)}</td><td class="right">${r.qty.toLocaleString()}</td><td class="right">${r.qty?yen(r.avg):'—'}</td><td class="right">${r.delta===null?'—':deltaHtml(r.delta)}</td></tr>`).join('')}
function fillSelect(id,vals){const el=document.getElementById(id);const first=el.querySelector('option')?.outerHTML||'';el.innerHTML=first+vals.map(v=>`<option>${v}</option>`).join('')}
let ledgerSort={key:'date',dir:-1};
function initFilters(){fillSelect('fMonth',Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0')));fillSelect('fSegment',[...new Set(DB.customers.map(x=>x.segment))].sort((a,b)=>a.localeCompare(b,'ja')));fillSelect('fProduct',DB.products.map(x=>x.name));fillSelect('fOrder',['通常','予約','緊急','追加','特別案件']);fillSelect('cSeg',[...new Set(DB.customers.map(x=>x.segment))].sort((a,b)=>a.localeCompare(b,'ja')));fillSelect('cmSeg',[...new Set(DB.customers.map(x=>x.segment))].sort((a,b)=>a.localeCompare(b,'ja')));fillSelect('sType',[...new Set(DB.suppliers.map(x=>x.type))].sort((a,b)=>a.localeCompare(b,'ja')));fillSelect('sRegion',[...new Set(DB.suppliers.map(x=>x.region))].sort((a,b)=>a.localeCompare(b,'ja')));fillSelect('pMonth',Array.from({length:12},(_,i)=>String(i+1).padStart(2,'0')));fillSelect('pProduct',DB.products.map(x=>x.name));fillSelect('pSupplier',DB.suppliers.map(x=>x.name).sort((a,b)=>a.localeCompare(b,'ja')));}
function renderLedger(){const y=fYear.value,m=fMonth.value,ds=fDate.value,seg=fSegment.value,prod=fProduct.value,ord=fOrder.value,q=fSearch.value.trim().toLowerCase();let a=DB.sales.filter(x=>(!y||x.year==y)&&(!m||String(x.month).padStart(2,'0')===m)&&(!ds||x.date===ds)&&(!seg||x.segment===seg)&&(!prod||x.product===prod)&&(!ord||x.orderType===ord)&&(!q||x.customer.toLowerCase().includes(q)));const spec=fLedgerSort.value||`${ledgerSort.key}:${ledgerSort.dir}`;a=sortRows(a,spec);ledgerCount.textContent=`${a.length.toLocaleString()}明細 / ${yen(sum(a,x=>x.amount))}`;ledgerRows.innerHTML=a.slice(0,1200).map(x=>`<tr><td>${jpDate(x.date)}</td><td>${x.time}</td><td>${x.customer}</td><td>${x.segment}</td><td>${pill(x.orderType)}</td><td>${x.channel}</td><td>${x.product}</td><td class="right">${yen(x.initialPrice)}</td><td class="right">${yen(x.price)}</td><td class="right">${x.markdownStep}</td><td class="right">${x.qty}</td><td class="right">${yen(x.amount)}</td></tr>`).join('')}
function comparePeriodSales(year){const level=cmpLevel.value,m=+cmpMonth.value,d=+cmpDay.value;if(level==='year')return DB.sales.filter(x=>x.year===year);if(level==='month')return DB.sales.filter(x=>x.year===year&&x.month===m);const last=new Date(year,m,0).getDate();if(d>last)return [];const ds=`${year}-${String(m).padStart(2,'0')}-${String(d).padStart(2,'0')}`;return DB.sales.filter(x=>x.date===ds)}
function comparePeriodText(year){const level=cmpLevel.value,m=+cmpMonth.value,d=+cmpDay.value;return level==='year'?`${year}年`:level==='month'?`${year}年${m}月`:`${year}年${m}月${d}日`}
function updateCompareControls(){const level=cmpLevel.value;cmpMonth.style.display=level==='year'?'none':'';cmpDay.style.display=level==='day'?'':'none';if(level==='day'){const y=+cmpYear.value,m=+cmpMonth.value,last=new Date(y,m,0).getDate(),old=+cmpDay.value||1;cmpDay.innerHTML=Array.from({length:last},(_,i)=>`<option value="${i+1}">${i+1}日</option>`).join('');cmpDay.value=String(Math.min(old,last))}}
function compareData(axis){const base=+cmpYear.value,prev=base-1,key=axis==='product'?'product':axis==='customer'?'customer':'segment',pa=entriesAgg(agg(comparePeriodSales(prev),key)),ba=entriesAgg(agg(comparePeriodSales(base),key)),pm=Object.fromEntries(pa.map(x=>[x.name,x])),bm=Object.fromEntries(ba.map(x=>[x.name,x]));return [...new Set([...Object.keys(pm),...Object.keys(bm)])].map(name=>{const p=pm[name]||{rev:0,qty:0},b=bm[name]||{rev:0,qty:0};return {name,prevRev:p.rev,baseRev:b.rev,prevQty:p.qty,baseQty:b.qty,delta:b.rev-p.rev,pct:p.rev?(b.rev-p.rev)/p.rev:(b.rev?9.99:0)}})}
function renderCompareHistory(){const base=+cmpYear.value,rows=DB.years.map(y=>{const a=comparePeriodSales(y),rev=sum(a,x=>x.amount),qty=sum(a,x=>x.qty),avg=qty?rev/qty:0,md=a.length?a.filter(x=>x.markdownStep>0).length/a.length:0;return {y,rev,qty,avg,md,label:comparePeriodText(y)}});barList('cmpHistoryBars',rows.map(x=>({name:String(x.y),rev:x.rev,qty:x.qty})),4);cmpHistoryRows.innerHTML=rows.map((r,i)=>{const prev=i?rows[i-1].rev:null,yoy=prev===null?'—':comparePct(prev,r.rev);return `<tr class="${r.y===base?'base-year':''}"><td><strong>${r.y}</strong>${r.y===base?' <span class="compare-badge">基準</span>':''}</td><td>${r.label}</td><td class="right">${yen(r.rev)}</td><td class="right">${r.qty.toLocaleString()}</td><td class="right">${r.qty?yen(r.avg):'—'}</td><td class="right">${r.rev?pct(r.md):'—'}</td><td class="right">${yoy}</td></tr>`}).join('')}
function renderYoy(){updateCompareControls();const base=+cmpYear.value,prev=base-1,b=comparePeriodSales(base),p=comparePeriodSales(prev),br=sum(b,x=>x.amount),pr=sum(p,x=>x.amount),bq=sum(b,x=>x.qty),pq=sum(p,x=>x.qty),bavg=bq?br/bq:0,pavg=pq?pr/pq:0,bmd=b.length?b.filter(x=>x.markdownStep>0).length/b.length:0,pmd=p.length?p.filter(x=>x.markdownStep>0).length/p.length:0;cmpPeriodLabel.textContent=`${comparePeriodText(base)} ⇔ ${comparePeriodText(prev)} を比較`;cmpPeriodNote.textContent=`同時に2023〜2026年の「${cmpLevel.value==='year'?'同一年次':cmpLevel.value==='month'?`${+cmpMonth.value}月`:`${+cmpMonth.value}月${+cmpDay.value}日`}」を横並び表示しています。`;yoyMetrics.innerHTML=[metric(`${comparePeriodText(base)} 売上`,yen(br),`${comparePeriodText(prev)}比 ${comparePct(pr,br)}`,br>=pr?'good':'bad'),metric(`${comparePeriodText(prev)} 売上`,yen(pr)),metric('売上増減',deltaHtml(br-pr)),metric('数量増減',`${bq-pq>=0?'+':''}${(bq-pq).toLocaleString()}本`,`平均実売 ${yen(pavg)} → ${yen(bavg)}`),metric('値下げ明細率',`${pct(pmd)} → ${pct(bmd)}`)].join('');renderCompareHistory();const cy=compareData('customer');growCust.innerHTML=changeList([...cy].sort((a,b)=>b.delta-a.delta).slice(0,10));declineCust.innerHTML=changeList([...cy].sort((a,b)=>a.delta-b.delta).slice(0,10));const pp=entriesAgg(agg(p,'product')),bp=entriesAgg(agg(b,'product')),pm=Object.fromEntries(pp.map(x=>[x.name,x])),bm=Object.fromEntries(bp.map(x=>[x.name,x]));const rr=[...new Set([...Object.keys(pm),...Object.keys(bm)])].map(name=>({name,delta:(bm[name]?.realization||0)-(pm[name]?.realization||0)})).sort((a,b)=>Math.abs(b.delta)-Math.abs(a.delta)).slice(0,10);priceRealization.innerHTML=rr.map(x=>`<div class="barlabel" style="padding:6px 0;border-bottom:1px solid var(--line)"><span>${x.name}</span><strong class="${x.delta>=0?'good':'bad'}">${x.delta>=0?'+':''}${(x.delta*100).toFixed(1)}pt</strong></div>`).join('')||'<div class="muted">データなし</div>';cmpPrevHead.textContent=`${comparePeriodText(prev)} 売上`;cmpBaseHead.textContent=`${comparePeriodText(base)} 売上`;cmpPrevQtyHead.textContent=`${prev}数量`;cmpBaseQtyHead.textContent=`${base}数量`;renderYoyTable()}
function changeList(a){return a.map((x,i)=>`<div class="barlabel" style="padding:6px 0;border-bottom:1px solid var(--line)"><span>${i+1}. ${x.name}</span><strong class="${x.delta>=0?'good':'bad'}">${x.delta>=0?'+':''}${yen(x.delta)}</strong></div>`).join('')||'<div class="muted">データなし</div>'}
function renderYoyTable(){let a=compareData(yoyAxis.value);const s=yoySort.value;a.sort((x,y)=>y[s]-x[s]);yoyRows.innerHTML=a.map(x=>`<tr><td>${x.name}</td><td class="right">${yen(x.prevRev)}</td><td class="right">${yen(x.baseRev)}</td><td class="right">${deltaHtml(x.delta)}</td><td class="right ${x.pct>=0?'good':'bad'}">${x.prevRev||x.baseRev?(x.pct*100).toFixed(1)+'%':'—'}</td><td class="right">${x.prevQty}</td><td class="right">${x.baseQty}</td></tr>`).join('')||'<tr><td colspan="7">データなし</td></tr>'}
